theme: jekyll-theme-minimal
title: Oglama
logo: /img/256.png
description: Private, community-driven web automation
google_analytics:
copyright_url: https://oglama.com/?ref=oglama.github.io
show_downloads: true
github:
    repository_nwo: "oglama/oglama"
    repository_url: https://github.com/oglama/oglama/
    repository_notice: https://github.com/oglama/oglama/blob/main/dist/NOTICE.md
    releases_url: https://github.com/oglama/oglama/releases/latest/
